src/search.cpp
Bench: 5094
ELO   | 104.17 +- 26.69 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=8MB
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 656 W: 388 L: 197 D: 71
=> Search changes

src/search.cpp
=> delta pruning

src/search.cpp
=> late move pruning ~40 Elo

src/evaluation.cpp, src/search.cpp, src/types.h
Bench: 5988
400 elo is probably just in selfplay not that much vs other engines
ELO   | 379.22 +- 83.55 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=8MB
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 232 W: 203 L: 18 D: 11
=> Ehm lol i guess there was a bug Bench: 5988

src/search.cpp
Bench: 4958
ELO   | 14.96 +- 8.85 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=8MB
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4880 W: 2115 L: 1905 D: 860
=> Higher value move sort

src/board.cpp, src/board.h, src/psqt.cpp, src/psqt.h, src/search.cpp, src/search.h, src/uci.cpp
some cleanups + speedups, also added `perft` for testing all perft positions
ELO   | 59.86 +- 19.59 (95%)
SPRT  | 1.0+0.01s Threads=1 Hash=8MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 1184 W: 655 L: 453 D: 76
Bench: 4462
=> speedup + perft testing

src/board.cpp, src/types.h
=> simplify castling

src/board.cpp
=> reorder operation sequence

src/psqt.cpp, src/psqt.h, src/search.cpp, src/uci.cpp
=> Killerscores

src/search.cpp
ELO   | 164.52 +- 36.35 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=8MB
GAMES | N: 424 W: 286 L: 99 D: 39
Bench: 1873078
=> new delta pruning conditions ~130 selfplay elo (lol?)

src/search.cpp
=> more null move pruning

src/board.cpp, src/search.cpp
=> Remove bumpy road

src/evaluation.cpp, src/helper.cpp, src/helper.h, src/search.cpp
=> automatic draw detection for KvK, KBvK, KNvK

src/psqt.cpp, src/psqt.h, src/search.cpp, src/uci.cpp
ELO   | 23.55 +- 8.35 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 2.50]
GAMES | N: 5392 W: 2358 L: 1993 D: 1041
Bench: 651429
=> more lmr reduction

src/board.cpp
=> small speedup

src/search.cpp
=> adjusting aspiration window

src/search.cpp, src/search.h
=> selectionSort for ab search

src/search.cpp
ELO   | 42.57 +- 11.45 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 2.50]
GAMES | N: 2912 W: 1356 L: 1001 D: 555
Bench: 6995201
=> check extension and removed condition

src/search.cpp, src/search.h, src/types.h
=> better nmp

src/search.cpp
=> new equation

src/search.cpp
=> adjusting window

src/board.cpp
=> better fen parsing

src/board.cpp, src/search.cpp, src/threadmanager.cpp, src/threadmanager.h, src/uci.cpp, src/uci.h
=> global searcher class

src/search.cpp
=> new history heuristic equation

src/Makefile, src/search.cpp, src/search.h, src/threadmanager.cpp, src/threadmanager.h, src/timemanager.cpp, src/timemanager.h, src/uci.cpp
moving the search time calculation in a seperate function that will make it easier in the future to make changes to the time calculation, it also supports a optimum time now and a maximum time which can be used in search
Bench: 2150799
=> move search time function

src/search.cpp
=> max 50ms searchtime for only 1 legalmove

src/benchmark.cpp, src/evaluation.cpp, src/search.cpp, src/search.h
this removes the player parameter in search
Bench: 2150799
=> remove player

src/search.cpp
=> higher lmr condition value

src/search.cpp, src/types.h
=> rewrote late move pruning condition

src/search.cpp
+ if we can access the tt use that as a better evaluation of the position, otherwise call evaluation
~20 elo 
Bench: 2304583
=> reverse futility pruning

src/search.cpp
=> lower null move pruning depth

src/search.cpp, src/search.h, src/timemanager.cpp, src/uci.cpp
=> use less time on obvious moves

src/search.cpp
=> negative history scores

src/board.cpp
ELO   | 12.62 +- 5.86 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 2.50]
GAMES | N: 9944 W: 3848 L: 3487 D: 2609
Bench: 2894553
=> faster draw

src/search.cpp, src/uci.cpp
=> uci movetime support

src/psqt.cpp
=> new pawn eval

src/psqt.cpp, src/uci.cpp
=> larger default hash + better material eval

src/psqt.cpp, src/psqt.h, src/search.cpp, src/uci.cpp
ELO   | 7.54 +- 5.55 (95%)
GAMES | N: 10088 W: 3501 L: 3282 D: 3305
=> lmr reduction with depth and mademoves

src/search.cpp, src/search.h, src/types.h
small cleanup and change the way the stack works
Bench: 2463966
=> cleanup and stack

src/search.cpp, src/search.h
ELO   | 26.47 +- 11.55 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 2144 W: 739 L: 576 D: 829
Bench: 2129306
=> improving variable + lower reverse fut margin

src/search.cpp
=> use previous eval for nullmoves

src/search.cpp, src/search.h
=> staticEval >=beta nmp

src/search.cpp, src/search.h
move the history updates to their own function.
Bench: 2071049
=> history updates

src/search.cpp
=> dont use nullmove eval

src/search.cpp, src/search.h
see algorithm based on logic from [weiss](https://github.com/TerjeKir/weiss)
ELO   | 44.78 +- 15.57 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 1256 W: 486 L: 325 D: 445
Bench: 1709827
=> see algorithm 

src/search.cpp
=> movecount pruning

src/search.cpp
Ordering moves higher that have a good see score and others lower.
=> see move ordering

src/search.cpp, src/uci.cpp
simplify tt read and write
Bench: 884657
=> simplify ttentry

src/search.cpp
=> simplify move scoring

src/search.cpp
=> see pruning in search

src/search.cpp
=> fix currentmove for nullmove

src/board.cpp, src/board.h
this patch is a small speedup
Bench: 696652
=> special qsearch functions

src/search.cpp, src/search.h, src/tt.cpp, src/tt.h
also fixing the saved move
Bench: 638646
=> seperate tt store code

src/search.h
=> small cleanup

src/uci.cpp
=> cleanup setoption

src/search.cpp, src/search.h, src/tt.cpp, src/tt.h
=> smaller TEntry and different replacement strategy

src/search.cpp, src/search.h
=> remove ply from absearch

src/search.cpp
=> various cleanups

src/search.cpp
=> newdepth variable

src/board.cpp, src/board.h, src/scores.cpp, src/scores.h, src/search.cpp, src/types.h, src/uci.cpp
ELO   | 3.24 +- 8.86 (95%)
LLR   | 3.05 (-2.94, 2.94) [-10.00, 0.00]
GAMES | N: 3536 W: 1078 L: 1045 D: 1413
Bench: 5483382
=> removing old code

src/search.cpp
=> goto moves loop

src/search.cpp
=> more pruning

src/search.cpp
=> lower razor margin

src/scores.cpp, src/scores.h
=> fix out of bounds access

src/board.cpp, src/perft.cpp, src/timemanager.h, src/types.h, src/uci.cpp, src/uci.h
=> uci code cleanup

src/search.cpp, src/search.h
=> pv in qsearch

src/search.cpp, src/search.h
=> skip checks in qsearch

src/search.cpp
=> skip early pruning for pvnodes

src/search.cpp
=> dont store entry at root

src/search.cpp
=> aspiration window cleanup

src/search.cpp
=> some more pruning

src/board.cpp, src/zobrist.h
=> simplify piece hash

src/board.cpp, src/board.h
=> fast and rough estimate for number of pseudo legal moves

src/search.cpp, src/search.h, src/tt.cpp
=> store mates in tt

src/search.cpp, src/tt.cpp, src/tt.h, src/uci.cpp, src/uci.h
=> better transposition table indexing

src/search.cpp, src/search.h
=> templated search + comments

src/search.cpp, src/search.h
=> history tweak

src/board.cpp, src/board.h, src/perft.cpp, src/types.h, src/uci.cpp, src/uci.h, src/ucioptions.cpp, src/ucioptions.h
=> ucioptions and almost automatic TUNE support

src/search.cpp
tune with https://github.com/dsekercioglu/weather-factory
Bench: 3011548
=> tune search values

src/search.cpp
=> reset spentEffort for new searches

src/board.cpp, src/board.h, src/perft.cpp, src/search.cpp, src/ucioptions.cpp
=> template cleanup

src/timemanager.cpp, src/timemanager.h, src/uci.cpp, src/ucioptions.cpp, src/ucioptions.h
=> support move overhead, default 10ms

src/board.cpp, src/board.h, src/search.cpp, src/types.h
=> print move simplification + fix no pv depth 1

src/uci.cpp, src/uci.h
=> fix memory leak that was caused because of exit(0)

src/board.h, src/neuralnet.cpp, src/neuralnet.h, src/search.cpp
=> pop accumulator in unmakemove

src/board.h, src/neuralnet.cpp, src/neuralnet.h, src/search.cpp
=> pop accumulator

src/board.cpp, src/board.h, src/evaluation.cpp, src/evaluation.h, src/neuralnet.cpp, src/neuralnet.h, src/search.cpp, src/search.h, src/timemanager.cpp, src/uci.cpp, src/ucioptions.cpp, src/ucioptions.h
=> namespace nnue and time fix

src/board.cpp, src/board.h, src/helper.cpp, src/helper.h, src/perft.cpp, src/search.cpp, src/uci.cpp
=> helper printmove

src/evaluation.cpp, src/evaluation.h, src/neuralnet.cpp, src/neuralnet.h, src/search.cpp, src/uci.cpp, src/ucioptions.cpp, src/ucioptions.h
=> Namespace nnue + output fix

src/board.cpp, src/board.h, src/neuralnet.cpp, src/neuralnet.h, src/search.cpp, src/uci.cpp
=> pop previous accumulator

src/Makefile, src/benchmark.cpp, src/benchmark.h, src/board.cpp, src/datagen.cpp, src/datagen.h, src/helper.cpp, src/helper.h, src/perft.cpp, src/perft.h, src/search.cpp, src/search.h, src/tt.cpp, src/tt.h, src/uci.cpp, src/uci.h, src/ucioptions.cpp, src/ucioptions.h
also change function names to camel case
Bench: 3395757
=> add date to executable

src/timemanager.cpp
=> fixing overhead for very low tc

.codescene/code-health-rules.json, src/datagen.h, src/evaluation.cpp, src/evaluation.h, src/perft.h, src/search.cpp, src/uci.cpp, src/ucicommands.cpp, src/ucicommands.h
=> cleanups in uci and eval

src/search.cpp
=> lmr improving

src/scores.cpp, src/scores.h, src/search.cpp
=> see changes

src/search.cpp, src/search.h, src/tt.cpp
=> history fix

src/board.cpp, src/board.h
ELO   | 14.22 +- 7.75 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 3912 W: 1073 L: 913 D: 1926
Bench: 3033777
=> movegen speedup

src/search.cpp
=> smaller history size

src/search.cpp
ELO   | 17.32 +- 8.67 (95%)
GAMES | N: 3072 W: 842 L: 689 D: 1541
Bench: 2555713
=> node count time

src/search.cpp, src/search.h
ELO   | 8.47 +- 5.63 (95%)
GAMES | N: 7096 W: 1808 L: 1635 D: 3653
Bench: 2558356
=> remove double see operation

src/board.cpp, src/board.h
=> remove redundant hash save in state

src/board.cpp, src/board.h
=> prefetch nmp

src/main.cpp, src/uci.cpp, src/uci.h, src/ucicommands.cpp, src/ucicommands.h
=> small uci cleanup

src/timemanager.cpp, src/timemanager.h
=> time double

src/board.cpp, src/helper.cpp, src/ucicommands.cpp
=> cleanup code style

src/search.cpp
=> remove mod op

src/board.cpp, src/board.h, src/search.cpp, src/types.h
=> Fast move check

src/board.cpp, src/board.h
=> remove double and op

src/search.cpp
ELO   | 5.47 +- 4.16 (95%)
GAMES | N: 12904 W: 3221 L: 3018 D: 6665
Bench: 3011322
=> lmr pvnode

README.md, src/datagen.cpp, src/search.cpp, src/ucicommands.cpp
=> fix go nodes

src/timemanager.cpp, src/timemanager.h
=> some overhead fixes and mtg

src/datagen.cpp, src/movegen.h, src/perft.cpp, src/search.cpp, src/search.h, src/tt.h, src/types.h, src/ucicommands.cpp
=> move sorting and MAX_MOVES = 128

src/board.cpp, src/movegen.cpp, src/movegen.h, src/nnue.cpp, src/nnue.h, src/search.cpp, src/types.h
=> static_cast + templating

src/board.cpp, src/board.h, src/uci.cpp
ELO   | 6.91 +- 9.74 (95%)
LLR   | 3.08 (-2.94, 2.94) [-10.00, 0.00]
GAMES | N: 2312 W: 571 L: 525 D: 1216
Bench: 2830193
=> board makemove cleanup

src/search.cpp
=> cleanup + more pruning

src/search.cpp, src/search.h
=> [Bugfix] data race

src/movegen.h
=> cleanup movegen order

src/movegen.h, src/perft.cpp
=> Remove useless movegen if

src/board.h, src/movegen.cpp, src/movegen.h, src/search.cpp, src/search.h, src/types.h, src/ucicommands.cpp
ELO   | 6.98 +- 4.99 (95%)
GAMES | N: 9304 W: 2421 L: 2234 D: 4649
Bench: 3124331
=> generate checks in qsearch depth 0

README.md, src/Makefile, src/datagen.cpp, src/randomFen.h, src/search.cpp, src/uci.cpp
```
ELO   | 4.71 +- 9.02 (95%)
LLR   | 3.02 (-2.94, 2.94) [-10.00, 0.00]
GAMES | N: 2880 W: 748 L: 709 D: 1423
```
Bench: 3124331
=> Restore data gen

src/timemanager.cpp
=> increase mtg for sudden death

src/timemanager.cpp
=> sudden death tc

src/movegen.h
=> simplfy en passant movegen

src/search.cpp, src/search.h
ELO   | 14.55 +- 7.90 (95%)
GAMES | N: 3776 W: 1040 L: 882 D: 1854
Bench: 3573662
=> prealloc movelists

src/evaluation.cpp, src/search.cpp, src/timemanager.cpp
=> multiple improvements and fixes

src/search.cpp, src/timemanager.cpp, src/timemanager.h
=> simplify tm

src/search.cpp, src/search.h, src/tt.cpp, src/tt.h
=> comments and tt cleanup

src/ucicommands.cpp, src/ucioptions.cpp, src/ucioptions.h
=> clear tt for ucinewgame

.github/workflows/smallbrain.yml, .github/workflows/smallbrain_binaries.yml, src/Makefile, src/main.cpp, src/ucicommands.cpp, src/ucicommands.h
=> upload binaries

.github/workflows/smallbrain.yml, .github/workflows/smallbrain_binaries.yml, src/Makefile, src/datagen.cpp, src/datagen.h, src/search.cpp, src/search.h, src/syzygy/Fathom/src/tbchess.c, src/syzygy/Fathom/src/tbprobe.c, src/timemanager.cpp, src/timemanager.h, src/uci.cpp, src/uci.h, src/ucicommands.cpp, src/ucicommands.h, src/ucioptions.cpp, src/ucioptions.h
=> better compiles, ci and tt fix

src/Makefile, src/ucicommands.cpp
=> new versioning and simplified makefile

src/movegen.cpp, src/movegen.h, src/search.cpp, src/types.h, src/ucicommands.cpp
=> remove movegen check

src/helper.cpp, src/helper.h, src/search.cpp
=> more debug commands

src/datagen.cpp, src/datagen.h, src/nnue.cpp, src/search.cpp
=> go nodes fix and datagen cleanup

src/benchmark.cpp, src/board.cpp, src/board.h, src/search.cpp
=> cleanup and position independent bench

src/board.cpp, src/board.h, src/main.cpp, src/nnue.cpp, src/nnue.h, src/types.h
=> nnue chunk updates and move updates

src/timemanager.cpp
=> half increment in tm

src/board.cpp, src/board.h, src/datagen.cpp, src/ucicommands.cpp
=> overload operator<< for board

src/search.cpp, src/search.h, src/tt.cpp, src/tt.h, src/types.h
=> cleanup tt usage

src/search.cpp, src/tt.cpp, src/types.h
=> catch value none tt save

src/search.cpp
=> dont research with same depth

src/benchmark.cpp, src/board.cpp, src/board.h, src/movegen.h, src/search.cpp, src/search.h
=> fix, cleanup, simplification

src/board.cpp
=> add pseudo legal checks

src/movepick.h
=> cleanup movepick

src/movepick.h, src/search.cpp
=> fix low time low depth move

src/movepick.h, src/search.cpp
=> possible fix for low depth moves

src/search.cpp, src/search.h
=> correctly reset threaddata

src/board.cpp, src/board.h, src/helper.cpp, src/helper.h, src/main.cpp, src/search.cpp, src/search.h, src/tt.cpp, src/tt.h, src/uci.cpp, src/uci.h, src/ucioptions.cpp, src/ucioptions.h
=> transposition table cleanup

src/search.cpp
=> fix qsearch check

src/board.cpp, src/helper.cpp, src/helper.h, src/movepick.h, src/search.cpp, src/uci.cpp
=> qsearch fix perhaps

src/movepick.h, src/search.cpp
=> fix pvnode pruning

src/search.cpp
=> save mates in tt

src/datagen.cpp, src/search.cpp, src/uci.cpp
=> repetition check output

src/search.cpp
=> triple fix

src/Makefile, src/benchmark.cpp, src/board.cpp, src/board.h, src/datagen.cpp, src/datagen.h, src/evaluation.cpp, src/evaluation.h, src/helper.cpp, src/helper.h, src/main.cpp, src/movegen.h, src/movepick.h, src/search.cpp, src/search.h, src/thread.cpp, src/thread.h, src/tt.cpp, src/tt.h, src/uci.cpp, src/uci.h, src/ucioptions.cpp
Thread Cleanup, removed ThreadData entirely
Replaced functions with generic ones
Changed names
Simplifications
Bench unchanged
Bench: 2796290
=> massive cleanup

.github/workflows/smallbrain.yml, .github/workflows/smallbrain_binaries.yml, src/board.cpp, src/board.h, src/search.cpp, src/tests.cpp, src/tests.h, src/thread.cpp, src/types.h, src/uci.cpp, src/uci.h, src/ucioptions.cpp
implement an isdrawn function
slight fix to repetition detection
added "unit" tests
update ci
Bench: 2795524
=> isdrawn function

src/Makefile, src/board.cpp, src/board.h, src/tests/tests.h
=> fix squares between array

src/thread.cpp
=> copy data from mainthread 

src/movegen.h, src/search.cpp
=> pretty print

src/movepick.h, src/search.cpp, src/search.h, src/thread.cpp, src/thread.h, src/uci.cpp, src/uci.h
=> uci searchmoves

src/uci.cpp, src/uci.h, src/ucioptions.cpp, src/ucioptions.h
=> simplify tuning

src/search.cpp
=> tune search vars

src/board.cpp, src/helper.h
bench changes because benchmark positions were not correctly set to chess960
Bench: 2692581
=> fix auto frc detection

src/search.cpp, src/search.h
=> probe tt first in qsearch and slight tb probing cleanup

src/benchmark.cpp, src/main.cpp, src/search.cpp, src/thread.cpp, src/thread.h, src/types.h, src/uci.cpp
=> move global variable to class

src/movegen.h
=> small movegen cleanup

src/datagen.cpp, src/datagen.h
=> unique_ptr in datagen

src/movepick.h, src/search.cpp, src/search.h, src/types.h
Bench: 3734449
ELO   | 13.22 +- 7.05 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 3944 W: 910 L: 760 D: 2274
=> const hist

src/thread.cpp
=> clear move heuristics in smp

src/board.h
=> small makeMove cleanup

src/board.h, src/movepick.h
=> movepick cleanup

src/search.cpp
=> lmr reduction capture

src/board.h
=> cleanup makemove

src/datagen.cpp, src/datagen.h, src/search.cpp, src/search.h
=> datagen speedup

src/board.cpp, src/board.h, src/datagen.cpp, src/search.cpp, src/tests/testDraw.h
=> less functions cleanup

README.md, src/board.h, src/datagen.cpp, src/datagen.h, src/main.cpp, src/rand.h, src/randomFen.cpp, src/randomFen.h, src/types.h, src/uci.cpp
=> datagen random improvements

src/search.cpp
=> time control comments

.github/workflows/smallbrain.yml, .github/workflows/smallbrain_binaries.yml, Makefile, README.md
move makefile one directory up
=> Seperate directory for build files

src/board.cpp, src/board.h, src/helper.cpp, src/helper.h, src/movegen.h, src/movepick.h, src/options.h, src/randomFen.cpp, src/search.cpp, src/str_utils.h, src/tests/testFenRepetition.h, src/uci.cpp
=> refactor: helper.h

src/board.cpp
=> fix: critical bug, loss of occupancy_bb_

src/movepick.h, src/search.cpp, src/search.h
=> feat: single move extension
