Disservin/Smallbrain

src/search.cpp
ELO   | 14.72 +- 6.42 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 2.50]
GAMES | N: 8408 W: 3316 L: 2960 D: 2132
Bench: 2220031
=> lmr refracture

src/search.cpp
by moving the output after the increment of the madeMoves variable.
No functional change.
=> Print correct currmovenumber starting with 1

src/board.cpp, src/search.cpp, src/tt.h, src/types.h, src/uci.cpp
this encodes a move into 16bits, this way each transposition entry is smaller and we can fit in more entries while keeping the hash size the same.
ELO   | 43.94 +- 14.94 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 1232 W: 438 L: 283 D: 511
=> 16 bit move

src/search.cpp
in same rare cases it was possible for the engine to prune all moves and return value_infinite which should never happen/isnt even allowed. This is now fixed.
Bench: 662315
=> fix stuck search

src/search.cpp, src/search.h
=> score qmove

src/uci.cpp
=> cleanup uci commands

src/search.cpp, src/search.h
slight speedup, this might have some very bad effects on very short time control..
but 4+0.04 works just fine...
Bench: 5483382
=> reduce TimePoint::now() calls

src/search.cpp
ELO   | 12.74 +- 7.50 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4912 W: 1554 L: 1374 D: 1984
=> nullmove pruning depth 

src/scores.cpp, src/search.cpp
=> beautify move scores

src/board.cpp, src/board.h, src/types.h
=> some more movegen cleanups

src/Makefile
i'll link the fix for the future..
debian system were getting a segfault when thread.join() is called
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52590
=> fix makefile for debian systems

src/search.cpp
This is a big search tune done with chess-tuning-tools and 11 parameters (which is insane!). 
The first 130 iterations were done by @TheBlackPlague (thanks again!), with rounds set to 128 and tc of 5+0.05 each iteration was taking about ~80 seconds on a 128thread (limited to 64 threads because of cutechess) machine! 
After very promising first results I continued with the tuning for another 60 iterations each taking ~400 seconds with 10 threads. There might be soom room left for further improvements in the future. 
A big thanks goes to @kiudee for his amazing tuner, chess-tuning-tools.
ELO   | 52.94 +- 16.69 (95%)
GAMES | N: 992 W: 365 L: 215 D: 412
The new values also gain at LTC.
Bench: 2909386
=> tune search constants

src/uci.cpp, src/uci.h
Thank you @vondele for pointing out that the TT is not initialised after allocation/reallocation.
This is now fixed.
ELO   | 9.65 +- 12.02 (95%)
LLR   | 3.03 (-2.94, 2.94) [-10.00, 0.00]
GAMES | N: 1872 W: 572 L: 520 D: 780
Bench: 2909386
=> initialise TT to zero

src/board.cpp, src/board.h, src/neuralnet.cpp, src/neuralnet.h, src/perft.cpp, src/search.cpp, src/search.h, src/types.h, src/uci.cpp
Bench: 3031886
1. bench is different because i removed the different sort function for qsearch moves, i think it didnt even work properly... i also checked with master and removing this there also generated Bench: 3031886 so all is fine 
2. i removed the entire move class struct, instead moves are now just `enums : int16_t` 
3. assigning a score to a move is a bit scuffed since i use now two arrays one to hold the moves and another to hold the values... i could probably make this into making each entry a tuple (move, score)
4. perft is now a bit faster for those who care.. it has a different makemove function that doesnt update the accumulator but i kept the zobrist hashing.. why ? idk.
5. some other stuff is a bit optimized too, like no repeating calls to the same function in movegen
=> performance patch

src/search.cpp, src/tt.cpp, src/tt.h
ELO   | 24.95 +- 10.91 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 2176 W: 684 L: 528 D: 964
Bench: 2646759
=> transposition table in qsearch

src/search.cpp
ELO   | 18.73 +- 9.21 (95%)
GAMES | N: 2896 W: 845 L: 689 D: 1362
Bench: 3213319
=> smaller delta in aspiration window

src/search.cpp
ELO   | 31.69 +- 12.28 (95%)
GAMES | N: 1616 W: 496 L: 349 D: 771
Bench: 2523517
=> linear depth bonus

src/search.cpp, src/search.h, src/timemanager.cpp
Changes in the time allocation so that an on going search can finish its last depth better.
ELO   | 21.31 +- 9.61 (95%)
GAMES | N: 2416 W: 655 L: 507 D: 1254
Bench: 2882442
=> finish last iterative depth search

src/search.cpp
ELO   | 9.60 +- 6.12 (95%)
GAMES | N: 6152 W: 1615 L: 1445 D: 3092
Bench: 3124331
=> use more time when bestmove fluctuates

src/timemanager.cpp
STC:
ELO   | 166.45 +- 31.47 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 312 W: 162 L: 23 D: 127
LTC:
ELO   | 154.14 +- 29.45 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
GAMES | N: 312 W: 150 L: 20 D: 142
Bench: 3124331
=> fix time usuage

src/board.cpp, src/board.h, src/movegen.h, src/movepick.h, src/perft.cpp, src/search.cpp, src/tests/testMoveLegality.h, src/types.h, src/uci.cpp
introduce support of the following syntax
```cpp
Movelist moves;
Movegen::legalmoves<Movetype::ALL>(board, moves);
for (auto ext : moves)
std::cout << ext.move << std::
```
and overload ostream << for move type
Bench: 2795524
=> range based iterators for movelist

src/search.cpp, src/search.h
Add singular extensions
```
ELO   | 10.49 +- 6.23 (95%)
GAMES | N: 5168 W: 1199 L: 1043 D: 2926
```
=> singular extensions

src/search.cpp
Thanks to Zuppa for letting me use Smallbrain on his OB instance.
The version of this patch without `result > -200` passed there, 
however I think the limiting factor is preventing excessive time usage in really lost positions and should still be an elo gainer.
```
ELO   | 5.03 +- 3.81 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 13536 W: 2970 L: 2774 D: 7792
```
Bench: 3729977
=> increase time when losing

src/timemanager.cpp
```
ELO   | 103.27 +- 22.92 (95%)
SPRT  | 40/8.0+0.08s Threads=1 Hash=16MB
GAMES | N: 464 W: 185 L: 51 D: 228
```
better time mangement in repeating time controls
Bench: 4020727
=> fix repeating tc 

src/board.cpp, src/board.h, src/datagen.cpp, src/types/state.h
also fixes a small hash bug, thus the change in bench.
Bench: 3866825
=> perf: remove second hash history keeping

src/board.cpp, src/board.h
Apply changes corresponding to https://github.com/Disservin/chess-library/pull/26 and https://github.com/Disservin/chess-library/pull/27.
The old `ply()` function must have always returned even values (and about twice the actual ply count). This now returns `1` for start pos, I hope that is OK.
Bench: 3812451
=> fix full move counter
